import { Template } from '../types';

export const TEMPLATES: Template[] = [
  {
    id: 'love-01',
    name: 'Love Template #01 - Pinky Promise',
    thumbnail: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-holding-hands-of-loved-one-40439-large.mp4',
    price: 199000,
    description: 'Tone hồng pastel ngọt ngào, hiệu ứng cánh hoa đào rơi chậm và bộ đếm ngày yêu nhau rực rỡ.',
    tag: 'totinh',
    features: ['Đếm ngày yêu thương', 'Hiệu ứng đào rơi', 'Thư tình gửi trao', 'Bộ sưu tập ảnh kỷ niệm'],
    themeColor: 'from-pink-100 to-rose-200',
    textColor: 'text-rose-600'
  },
  {
    id: 'love-02',
    name: 'Love Template #02 - Eternal Lights',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-couple-under-the-sparklers-at-night-41586-large.mp4',
    price: 249000,
    description: 'Hiệu ứng ánh sáng lung linh huyền ảo trên nền tím đêm hoàng hôn, cực kỳ sang trọng và ấm áp.',
    tag: 'kyniem',
    features: ['Nhạc nền ballad tự chọn', 'Timeline hành trình yêu', 'Lời chúc từ bạn bè', 'Video kỷ niệm'],
    themeColor: 'from-purple-100 to-indigo-200',
    textColor: 'text-indigo-600'
  },
  {
    id: 'love-03',
    name: 'Love Template #03 - Starry Night Love',
    thumbnail: 'https://images.unsplash.com/photo-1501901604252-2c368c50bad4?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-couple-sitting-by-the-campfire-40405-large.mp4',
    price: 299000,
    description: 'Nền trời sao lấp lánh động, biểu tượng cung hoàng đạo đôi và đồng hồ đếm ngược từng giây.',
    tag: 'cauhon',
    features: ['Sao băng nguyện ước', 'Đồng hồ đếm ngược giây', 'Lời ngỏ chân thành', 'Bản đồ nơi đầu tiên gặp'],
    themeColor: 'from-slate-900 via-purple-900 to-slate-900',
    textColor: 'text-pink-400'
  },
  {
    id: 'love-04',
    name: 'Love Template #04 - Minimalist Romance',
    thumbnail: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-hands-drawing-a-heart-shape-41594-large.mp4',
    price: 149000,
    description: 'Phong cách tối giản, tinh tế với phông chữ Serif quý phái và những khoảng trống bay bổng.',
    tag: 'totinh',
    features: ['Font chữ cổ điển', 'Lời ngỏ một trang', 'Hiệu ứng fade-in nhẹ', 'Phát nhạc tự động'],
    themeColor: 'from-neutral-50 to-amber-50',
    textColor: 'text-neutral-800'
  },
  {
    id: 'love-05',
    name: 'Love Template #05 - Sweet Memories Birthday',
    thumbnail: 'https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-happy-girl-blowing-candles-on-birthday-cake-40432-large.mp4',
    price: 199000,
    description: 'Mẫu đặc biệt chúc mừng sinh nhật người thương, pháo hoa nổ lung linh rực rỡ.',
    tag: 'sinhnhat',
    features: ['Bắn pháo hoa động', 'Hộp quà ảo mở ra thư', 'Lời chúc từ người yêu', 'Album ảnh rực rỡ'],
    themeColor: 'from-pink-50 to-amber-100',
    textColor: 'text-amber-700'
  },
  {
    id: 'love-06',
    name: 'Love Template #06 - Love Journey Diary',
    thumbnail: 'https://images.unsplash.com/photo-1518568747007-d77987081145?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-couple-hugging-and-laughing-in-the-snow-40417-large.mp4',
    price: 279000,
    description: 'Dạng nhật ký hành trình cuộn dọc, lật mở từng kỷ niệm theo dòng thời gian lãng mạn.',
    tag: 'kyniem',
    features: ['Nhật ký hành trình', 'Hiệu ứng tuyết rơi', 'Bản đồ tình yêu', 'Trích dẫn hay mỗi ngày'],
    themeColor: 'from-blue-50 to-pink-100',
    textColor: 'text-pink-600'
  },
  {
    id: 'love-07',
    name: 'Love Template #07 - Marry Me, Darling',
    thumbnail: 'https://images.unsplash.com/photo-1529636798458-921a226247f2?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-proposal-ring-being-put-on-a-finger-41589-large.mp4',
    price: 399000,
    description: 'Mẫu thiết kế cầu hôn đặc biệt với nút bấm Yes/No tương tác vui nhộn (nút No sẽ chạy trốn khi di chuột).',
    tag: 'cauhon',
    features: ['Nút chọn Yes/No vui nhộn', 'Mưa trái tim 3D', 'Lời thề hẹn ước', 'Ghi nhận câu trả lời'],
    themeColor: 'from-purple-100 via-rose-100 to-amber-100',
    textColor: 'text-purple-600'
  },
  {
    id: 'love-08',
    name: 'Love Template #08 - Sunset Sparkle',
    thumbnail: 'https://images.unsplash.com/photo-1494972308805-463bc619d34e?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-couple-by-the-sea-during-a-golden-sunset-41604-large.mp4',
    price: 199000,
    description: 'Tông màu cam hoàng hôn ấm áp và thơ mộng, kèm hiệu ứng gợn sóng nước êm đềm dập dìu.',
    tag: 'totinh',
    features: ['Bộ đếm ngày yêu', 'Hiệu ứng gợn sóng', 'Thư tình âm nhạc', 'Slide ảnh lướt nhẹ'],
    themeColor: 'from-orange-100 to-rose-200',
    textColor: 'text-rose-700'
  },
  {
    id: 'love-09',
    name: 'Love Template #09 - Cute Chibi Love',
    thumbnail: 'https://images.unsplash.com/photo-1507504038482-76210f5c2f0a?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-drawing-a-heart-with-sparklers-41595-large.mp4',
    price: 179000,
    description: 'Phong cách hoạt hình dễ thương, hoạt họa mèo Chibi ngộ nghĩnh mừng sinh nhật hoặc tỏ tình.',
    tag: 'sinhnhat',
    features: ['Mèo chibi động dễ thương', 'Bóng bay màu sắc', 'Phát bài hát Happy Birthday', 'Trò chơi mini đập bong bóng'],
    themeColor: 'from-yellow-50 to-pink-100',
    textColor: 'text-rose-500'
  },
  {
    id: 'love-10',
    name: 'Love Template #10 - Golden Hours',
    thumbnail: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-holding-hands-of-loved-one-40439-large.mp4',
    price: 249000,
    description: 'Giao diện hoàng kim lấp lánh, phông nền mờ ảo (glassmorphism) và đường viền kim cương tinh xảo.',
    tag: 'kyniem',
    features: ['Kính mờ sang trọng', 'Hiệu ứng hạt vàng bay', 'Đếm ngày yêu cao cấp', 'Trưng bày ảnh nghệ thuật'],
    themeColor: 'from-amber-50 to-rose-100',
    textColor: 'text-amber-800'
  },
  // Adding remaining 20 templates to make up to 30 for complete demo and infinite scroll
  {
    id: 'love-11',
    name: 'Love Template #11 - Violet Serenade',
    thumbnail: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-couple-under-the-sparklers-at-night-41586-large.mp4',
    price: 189000,
    description: 'Tone tím violet sâu lắng thơ mộng, các nốt nhạc rơi nhẹ theo bài tình ca du dương.',
    tag: 'totinh',
    features: ['Nốt nhạc bay bổng', 'Trình phát nhạc lãng mạn', 'Thư ngỏ giấu kín', 'Gửi lời phản hồi'],
    themeColor: 'from-violet-100 to-fuchsia-200',
    textColor: 'text-violet-700'
  },
  {
    id: 'love-12',
    name: 'Love Template #12 - Rose Romance',
    thumbnail: 'https://images.unsplash.com/photo-1518568747007-d77987081145?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-hands-drawing-a-heart-shape-41594-large.mp4',
    price: 220000,
    description: 'Hiệu ứng cánh hoa hồng nhung đỏ thắm rơi đầy màn hình, thích hợp cho ngày kỷ niệm yêu nhau.',
    tag: 'kyniem',
    features: ['Cánh hồng đỏ rơi bay', 'Đếm ngày tình yêu', 'Album lưới hiện đại', 'Trích dẫn tình yêu'],
    themeColor: 'from-red-50 to-rose-200',
    textColor: 'text-rose-700'
  },
  {
    id: 'love-13',
    name: 'Love Template #13 - Neon Night Beats',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-drawing-a-heart-with-sparklers-41595-large.mp4',
    price: 269000,
    description: 'Phong cách Cyberpunk neon rực rỡ với trái tim đập theo nhịp lo-fi trẻ trung và cá tính.',
    tag: 'totinh',
    features: ['Đèn neon nhấp nháy', 'Nhạc lo-fi chill', 'Hiệu ứng nhiễu sóng', 'Đồng hồ đếm ngược'],
    themeColor: 'from-slate-900 via-indigo-950 to-purple-900',
    textColor: 'text-pink-500'
  },
  {
    id: 'love-14',
    name: 'Love Template #14 - Cherry Blossom',
    thumbnail: 'https://images.unsplash.com/photo-1507504038482-76210f5c2f0a?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-holding-hands-of-loved-one-40439-large.mp4',
    price: 199000,
    description: 'Phong cách Nhật Bản thanh lịch với hoa anh đào rơi và phông chữ nét vẽ cọ nghệ thuật.',
    tag: 'sinhnhat',
    features: ['Hoa anh đào rơi', 'Nét vẽ phác họa đôi', 'Nhạc không lời nhẹ nhàng', 'Hộp thư bí mật'],
    themeColor: 'from-rose-50 to-pink-100',
    textColor: 'text-rose-600'
  },
  {
    id: 'love-15',
    name: 'Love Template #15 - Ocean Breeze',
    thumbnail: 'https://images.unsplash.com/photo-1529636798458-921a226247f2?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-couple-by-the-sea-during-a-golden-sunset-41604-large.mp4',
    price: 215000,
    description: 'Giao diện xanh ngọc dịu mát, âm thanh sóng biển rì rào cùng câu chuyện tình yêu đầy tự do.',
    tag: 'kyniem',
    features: ['Tiếng sóng biển rì rào', 'Bản đồ bờ biển kỷ niệm', 'Thư tay thả chai thủy tinh', 'Album ảnh dạng trượt'],
    themeColor: 'from-cyan-50 to-sky-100',
    textColor: 'text-sky-700'
  },
  {
    id: 'love-16',
    name: 'Love Template #16 - Diamond Promise',
    thumbnail: 'https://images.unsplash.com/photo-1501901604252-2c368c50bad4?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-proposal-ring-being-put-on-a-finger-41589-large.mp4',
    price: 350000,
    description: 'Trải nghiệm cầu hôn trực tuyến trang trọng với phông chữ luxury mạ vàng lấp lánh.',
    tag: 'cauhon',
    features: ['Viền nhẫn kim cương lấp lánh', 'Hỏi cưới tương tác', 'Thư nguyện ước trọn đời', 'Danh sách khách mời ảo'],
    themeColor: 'from-neutral-900 via-stone-800 to-neutral-900',
    textColor: 'text-amber-500'
  },
  {
    id: 'love-17',
    name: 'Love Template #17 - Pastel Dreamland',
    thumbnail: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-couple-sitting-by-the-campfire-40405-large.mp4',
    price: 180000,
    description: 'Sự kết hợp hoàn hảo giữa 3 màu pastel ngọt lịm, bong bóng xà phòng bay nhẹ thẩn thơ.',
    tag: 'totinh',
    features: ['Bong bóng xà phòng động', 'Thiệp viết tay dễ thương', 'Màn hình khóa nhập mật khẩu sinh nhật', 'Nhạc lofi ngọt ngào'],
    themeColor: 'from-pink-100 via-purple-100 to-blue-100',
    textColor: 'text-purple-600'
  },
  {
    id: 'love-18',
    name: 'Love Template #18 - Golden Anniversary',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-couple-under-the-sparklers-at-night-41586-large.mp4',
    price: 299000,
    description: 'Dành riêng cho ngày kỷ niệm năm yêu nhau, tràn ngập ánh đèn lấp lánh và đếm ngược rạng ngời.',
    tag: 'kyniem',
    features: ['Hiệu ứng pháo giấy confetti', 'Cột mốc sự kiện hành trình', 'Lời cảm ơn người thương', 'Slide ảnh lướt chạm mượt'],
    themeColor: 'from-amber-100 via-rose-50 to-amber-100',
    textColor: 'text-amber-800'
  },
  {
    id: 'love-19',
    name: 'Love Template #19 - Watercolor Love',
    thumbnail: 'https://images.unsplash.com/photo-1518568747007-d77987081145?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-hands-drawing-a-heart-shape-41594-large.mp4',
    price: 199000,
    description: 'Phong cách tranh màu nước vẽ tay vô cùng lãng mạn, nhẹ nhàng, tựa như câu chuyện cổ tích.',
    tag: 'totinh',
    features: ['Hiệu ứng vẽ loang màu nước', 'Khung ảnh gỗ vintage', 'Bản nhạc dương cầm du dương', 'Hộp quà chứa lời tâm sự'],
    themeColor: 'from-rose-50 via-teal-50 to-rose-100',
    textColor: 'text-rose-600'
  },
  {
    id: 'love-20',
    name: 'Love Template #20 - Sweet Macaron',
    thumbnail: 'https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-happy-girl-blowing-candles-on-birthday-cake-40432-large.mp4',
    price: 169000,
    description: 'Mẫu mừng sinh nhật dễ thương với bảng màu bánh ngọt ngon mắt, hiệu ứng nến lung linh.',
    tag: 'sinhnhat',
    features: ['Cắt bánh kem sinh nhật tương tác', 'Gửi lời chúc ẩn danh', 'Thư tay của gấu', 'Hiệu ứng kẹo ngọt rơi'],
    themeColor: 'from-yellow-50 via-pink-100 to-rose-50',
    textColor: 'text-rose-600'
  },
  {
    id: 'love-21',
    name: 'Love Template #21 - Starry Moonlit',
    thumbnail: 'https://images.unsplash.com/photo-1501901604252-2c368c50bad4?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-couple-sitting-by-the-campfire-40405-large.mp4',
    price: 259000,
    description: 'Nền trăng tròn lấp lánh và ngàn sao lộng gió, cực kỳ bay bổng cho lứa đôi ước hẹn.',
    tag: 'cauhon',
    features: ['Trăng tròn phát sáng', 'Bụi sao bay lấp lánh', 'Lời thề hứa lãng mạn', 'Bản đồ thiên văn tình yêu'],
    themeColor: 'from-neutral-950 via-purple-950 to-neutral-900',
    textColor: 'text-pink-300'
  },
  {
    id: 'love-22',
    name: 'Love Template #22 - Polaroid Memories',
    thumbnail: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-holding-hands-of-loved-one-40439-large.mp4',
    price: 189000,
    description: 'Phong cách album ảnh chụp lấy ngay Polaroid hoài cổ, lưu giữ trọn vẹn từng khoảnh khắc ngọt ngào.',
    tag: 'kyniem',
    features: ['Khung ảnh Polaroid cổ điển', 'Lời ghi chú viết bằng bút mực', 'Nhạc băng cassette hoài niệm', 'Bộ đếm ngày phong cách cơ học'],
    themeColor: 'from-stone-100 via-orange-50 to-stone-100',
    textColor: 'text-stone-800'
  },
  {
    id: 'love-23',
    name: 'Love Template #23 - Infinite Hearts',
    thumbnail: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-hands-drawing-a-heart-shape-41594-large.mp4',
    price: 199000,
    description: 'Hiệu ứng trái tim vô cực 3D bay từ tâm màn hình tỏa ra xung quanh đầy mê hoặc.',
    tag: 'totinh',
    features: ['Trái tim 3D bay vô tận', 'Giao diện kính mờ mộng mơ', 'Bức thư tỏ tình lướt cuộn', 'Nút tim tương tác tăng điểm yêu'],
    themeColor: 'from-pink-100 via-rose-100 to-red-100',
    textColor: 'text-red-600'
  },
  {
    id: 'love-24',
    name: 'Love Template #24 - Sparkle Confetti',
    thumbnail: 'https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-happy-girl-blowing-candles-on-birthday-cake-40432-large.mp4',
    price: 179000,
    description: 'Pháo giấy lấp lánh tung bay mỗi khi cuộn trang, mang đến bầu không khí ngập tràn hạnh phúc mừng tuổi mới.',
    tag: 'sinhnhat',
    features: ['Pháo giấy confetti bay động', 'Thiệp mừng 3D mở ra', 'Slide ảnh lật trang sách', 'Bảng đếm ngược sinh nhật'],
    themeColor: 'from-amber-50 via-rose-50 to-indigo-100',
    textColor: 'text-indigo-700'
  },
  {
    id: 'love-25',
    name: 'Love Template #25 - Midnight Promise',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-couple-under-the-sparklers-at-night-41586-large.mp4',
    price: 299000,
    description: 'Bản tình ca lúc nửa đêm, bầu trời ngập ánh sao lung linh cùng những bức thư tay bí mật thắp sáng.',
    tag: 'cauhon',
    features: ['Hiệu ứng đóm đóm bay lung linh', 'Thư tình bí mật lấp lánh', 'Bộ ảnh đôi tràn màn hình', 'Trình phát nhạc đĩa than'],
    themeColor: 'from-slate-950 via-indigo-950 to-slate-900',
    textColor: 'text-indigo-300'
  },
  {
    id: 'love-26',
    name: 'Love Template #26 - Rose Gold Glam',
    thumbnail: 'https://images.unsplash.com/photo-1518568747007-d77987081145?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-proposal-ring-being-put-on-a-finger-41589-large.mp4',
    price: 320000,
    description: 'Tông màu vàng hồng (rose gold) cao cấp, cực kỳ sang trọng, thích hợp cho ngày kỷ niệm trọng đại.',
    tag: 'kyniem',
    features: ['Giao diện mạ vàng hồng quý phái', 'Timeline các dấu mốc thời gian', 'Trình phát video mượt mà', 'Biểu đồ nhịp đập con tim'],
    themeColor: 'from-rose-100 via-amber-100 to-rose-200',
    textColor: 'text-rose-800'
  },
  {
    id: 'love-27',
    name: 'Love Template #27 - Love Letterbox',
    thumbnail: 'https://images.unsplash.com/photo-1507504038482-76210f5c2f0a?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-hands-drawing-a-heart-shape-41594-large.mp4',
    price: 159000,
    description: 'Hộp thư tình yêu ngọt ngào, người dùng có thể nhấp mở phong bì thư để đọc lời tâm tình đầy lãng mạn.',
    tag: 'totinh',
    features: ['Phong bì thư gấp mở ảo diệu', 'Cánh hoa rơi rải rác', 'Ký tên tình yêu điện tử', 'Bộ sưu tập ảnh kỷ niệm'],
    themeColor: 'from-pink-50 via-rose-50 to-pink-100',
    textColor: 'text-rose-600'
  },
  {
    id: 'love-28',
    name: 'Love Template #28 - Star Map Waltz',
    thumbnail: 'https://images.unsplash.com/photo-1501901604252-2c368c50bad4?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-young-couple-sitting-by-the-campfire-40405-large.mp4',
    price: 279000,
    description: 'Bản hòa tấu dưới bầu trời sao, hiển thị bản đồ chòm sao ngày hai bạn chính thức thuộc về nhau.',
    tag: 'kyniem',
    features: ['Bản đồ chòm sao tương tác', 'Vũ điệu tình yêu xoay tròn', 'Lời chúc chèn nhạc nền', 'Đồng hồ đếm ngày'],
    themeColor: 'from-slate-950 via-purple-950 to-indigo-950',
    textColor: 'text-purple-300'
  },
  {
    id: 'love-29',
    name: 'Love Template #29 - Lavender Fields',
    thumbnail: 'https://images.unsplash.com/photo-1529636798458-921a226247f2?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-couple-by-the-sea-during-a-golden-sunset-41604-large.mp4',
    price: 199000,
    description: 'Cánh đồng oải hương lãng mạn, hiệu ứng phấn hoa tím rơi bay bổng cực kỳ nhẹ nhàng dịu mắt.',
    tag: 'totinh',
    features: ['Hiệu ứng cánh hoa tím rơi', 'Thư tình ngập sắc oải hương', 'Bộ ảnh kỷ niệm ấm áp', 'Đếm ngược ngày kỷ niệm'],
    themeColor: 'from-violet-50 via-fuchsia-50 to-purple-100',
    textColor: 'text-purple-700'
  },
  {
    id: 'love-30',
    name: 'Love Template #30 - Sweet Balloon Party',
    thumbnail: 'https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?w=600&auto=format&fit=crop&q=80',
    previewVideo: 'https://assets.mixkit.co/videos/preview/mixkit-happy-girl-blowing-candles-on-birthday-cake-40432-large.mp4',
    price: 189000,
    description: 'Mẫu thiết kế ngập bóng bay nhiều màu sắc bay vút lên cao mừng sinh nhật ngọt ngào của nửa kia.',
    tag: 'sinhnhat',
    features: ['Bóng bay bay lên liên tục', 'Hộp quà lật mở chúc mừng', 'Album ảnh rực rỡ sắc màu', 'Nhạc nền mừng sinh nhật vui tươi'],
    themeColor: 'from-pink-100 via-amber-50 to-rose-100',
    textColor: 'text-rose-600'
  }
];
